spring:
  application:
    name: reservalab
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    # url: jdbc:postgresql://resrevalab-database.ctkqkcec8dck.us-east-2.rds.amazonaws.com:5432/reservalab

    url: jdbc:postgresql://localhost:5432/reservalab
    username: postgres
    password: talikdnt123

security:
  jwt:
    expiration: 120
    signing-key: my-secret-key
    # url: jdbc:postgresql://resrevalab-database.ctkqkcec8dck.us-east-2.rds.amazonaws.com:5432/reservalab
