spring:
  application:
    name: reservalab
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/reservalab
    username: postgres
    password: talikdnt123
