spring:
  application:
    name: reservalab
  security:
    oauth2:
      client:
        provider:
          my-client:
            authorization-uri: http://localhost:8080/oauth2/authorize
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5433/reservalab
    username: postgres
    password: postgres
