spring:
  application:
    name: reservalab
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5433/reservalab
    username: postgres
    password: postgres

security:
  jwt:
    expiration: 120
    signing-key: my-secret-key
